[config]
version = "2"

[mqtt.bridge]
built_in = true

[logs]
path = "/var/log/tedge"

[tmp]
path = "/tmp"

[data]
path = "/tmp/tedge"

[log]
plugin_paths = ["@CONFIG_DIR@/log-plugins", "/usr/share/tedge/log-plugins"]

[diag]
plugin_paths = ["@CONFIG_DIR@/diag-plugins", "/usr/share/tedge/diag-plugins"]
