#!/bin/sh -e
touch "/var/log/tedge-mapper-c8y.log"
DAEMON_USER="root"
LOG_FILE="/var/log/tedge-mapper-c8y.log"
PIDFILE="/run/lock/tedge-mapper-c8y.lock"
BIN="/data/tedge/bin"
CONFIG_DIR="/data/tedge"

if [ -f /data/tedge/env ]; then
    set -a
    # shellcheck disable=SC1091
    . /data/tedge/env
    set +a
fi

mkdir -p /run/lock
chown 1777 /run/lock
touch "$PIDFILE"
"$BIN/tedge" --config-dir "$CONFIG_DIR" init --user root --group root ||:

if [ -n "$DAEMON_USER" ]; then
    chown "$DAEMON_USER" "$PIDFILE"
    chown "$DAEMON_USER" "/var/log/tedge-mapper-c8y.log"
fi
exec chpst -u "$DAEMON_USER" "$BIN/tedge-mapper" --config-dir "$CONFIG_DIR" c8y >> "$LOG_FILE" 2>&1