#!/bin/sh -e
touch "/var/log/tedge.log"
DAEMON_USER="root"
LOG_FILE="/var/log/tedge.log"
LOCK_DIR=/var/run/lock
if [ -d /var/run ]; then
    LOCK_DIR=/var/run/lock
elif [ -d /run/lock ]; then
    LOCK_DIR=/run/lock
fi
PIDFILE="$LOCK_DIR/tedge.lock"
BIN="@CONFIG_DIR@/bin"
CONFIG_DIR="@CONFIG_DIR@"

if [ -f "$CONFIG_DIR/env" ]; then
    # shellcheck disable=SC1091
    . "$CONFIG_DIR/env"
fi

mkdir -p "$LOCK_DIR"
chown 1777 "$LOCK_DIR"
touch "$PIDFILE"
"$BIN/tedge" init --user root --group root ||:

if [ -n "$DAEMON_USER" ]; then
    chown "$DAEMON_USER" "$PIDFILE"
    chown "$DAEMON_USER" "/var/log/tedge.log"
fi
exec chpst -u "$DAEMON_USER" "$BIN/tedge" run all c8y >> "$LOG_FILE" 2>&1