#!/bin/sh
set -e

CONFIG_DIR="@CONFIG_DIR@"

if [ -f "$CONFIG_DIR/env" ]; then
    # shellcheck disable=SC1091
    . "$CONFIG_DIR/env"
fi

manage_initd() {
    command="$1"
    name="$2"

    # check for non-service related actions first
    case "$command" in
        restart_device)
            sync; sync;
            sleep 2;
            reboot;
            exit 0
            ;;
    esac

    SOURCE_SCRIPT=$(find "$CONFIG_DIR/services-init.d" -name "*$name" | head -n1)
    SERVICE_SCRIPT=$(find /etc/init.d -name "*$name" | head -n1)
    if [ -z "$SERVICE_SCRIPT" ]; then
        # use default location
        SERVICE_SCRIPT="/etc/init.d/$(basename "$SOURCE_SCRIPT")"
    fi

    case "$command" in
        is_available)
            exit 0
            ;;
        start)
            "$SERVICE_SCRIPT" start
            ;;
        stop)
            # don't stop a service that does not exist
            if [ -f "$SERVICE_SCRIPT" ]; then
                "$SERVICE_SCRIPT" stop
            fi
            ;;
        restart)
            # tedge connect will do a restart then enable the service
            manage_initd enable "$name" ||:
            "$SERVICE_SCRIPT" restart
            ;;
        enable)
            ln -sf "$SOURCE_SCRIPT" "$SERVICE_SCRIPT"
            ;;
        disable)
            rm -f "$SERVICE_SCRIPT"
            ;;
        is_active|status)
            "$SERVICE_SCRIPT" status
            ;;
        *) echo "Unsupported command. command=$command"; exit 1 ;;
    esac
}

##############################
# Main
##############################
COMMAND="$1"
SERVICE_NAME=""
if [ $# -ge 2 ]; then
    SERVICE_NAME="$2"
fi
manage_initd "$COMMAND" "$SERVICE_NAME"
