#!/bin/sh -e
touch "/var/log/mosquitto.log"
DAEMON_USER="root"
LOG_FILE="/var/log/mosquitto.log"
PIDFILE="/run/lock/mosquitto.lock"
BIN="@CONFIG_DIR@/bin"
CONFIG_DIR="@CONFIG_DIR@"

if [ -f "$CONFIG_DIR/env" ]; then
    set -a
    # shellcheck disable=SC1091
    . "$CONFIG_DIR/env"
    set +a
fi

mkdir -p /run/lock
chown 1777 /run/lock
touch "$PIDFILE"
"$BIN/tedge" init --user root --group root ||:

if [ -n "$DAEMON_USER" ]; then
    chown "$DAEMON_USER" "$PIDFILE"
    chown "$DAEMON_USER" "/var/log/mosquitto.log"
fi
exec chpst -u "$DAEMON_USER" "$BIN/mosquitto" -c @CONFIG_DIR@/mosquitto.conf >> "$LOG_FILE" 2>&1