name: build

on:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  TEDGE_CHANNEL: release

jobs:
  build:
    name: Build ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          target:
            - arch: aarch64-linux-musl
              name: arm64
            - arch: arm-linux-musleabihf
              name: armhf
            - arch: arm-linux-musleabi
              name: armel
            - arch: x86_64-linux
              name: amd64
            - arch: x86-linux
              name: i386
            - arch: riscv64-linux
              name: riscv64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@just
      - name: Build (with upx)
        run: just build ${{ matrix.target.arch }} ${{ matrix.target.name }}
      - name: Build (without upx)
        run: just build ${{ matrix.target.arch }} ${{ matrix.target.name }}-noupx --skip-upx

      - name: Upload packages as zip
        # https://github.com/marketplace/actions/upload-a-build-artifact
        uses: actions/upload-artifact@v4
        with:
            name: tedge-standalone-${{ matrix.target.name }}
            path: |
              tedge-standalone-${{ matrix.target.name }}-noupx.tar.gz
              tedge-standalone-${{ matrix.target.name }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    if: |
      always() &&
      startsWith(github.ref, 'refs/tags/') &&
      needs.build.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: tmp/
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: false
          draft: true
          files: |
            tmp/**/*.tar.gz
